### ISSUE TITLE
mdf files will not open in editor

### ISSUE THREAD

**Issue by Dusty14** [BlueAndi/vscp-framework#18]
Hello,
I am trying to open a mdf (xml) file in the vscp editor but not one file will successfully read. 
I have 13.1.0.10, I try to open the file under the vscp-arduino-0.7.0/mdf_template.xml using the vscp MDF editor but it returns nothing. I had to fix a couple of issues in the file according to w3schools syntax checker. Also if I try using a local mdf in the configuration window, it starts reading and stops with "Reading standard registers of device 1/8" and then "Failed to read standard registers of device"
This is also true for any xml file I try to open using any of the vscp firmware as well. Am I missing something here or is it a bug in vscp works?
Also the link in the xml pointing to the schema on your website is down.

**Comment by BlueAndi** [comment]
Hi,
to be honest, I never tried the mdf editor. But I just checked it some minutes ago with Aluminium 13.1.0.10 release and yes, its not working.

Regarding the mdf_template.xml you are right, it contains some errors. I already fixed and pushed them. The schema location was updated.

I guess the message "Reading standard registers of device 1/8" has nothing to do with the xml file. Do you have the vscp daemon running too? You could try to read the registers with the web interface.

**Comment by BlueAndi** [comment]
BTW do you see the heartbeat events (period is 30s) in the vscp client window? How do you connect to the communication bus?

**Comment by Dusty14** [comment]
G'day,
Thanks for the reply, I feel a bit better now having someone verify this. To be honest, I have been struggling to get grips on VSCP a bit through the other site. Its a bit overwhelming at first and many things dont seem to function as expected. I was pushing to use VSCP_LEVEL_II in my project because of the data needs and also because I am not using CAN but rather ethernet. All my devices are ESPs and Raspberry Pis. The VSCP Works and especially the VSCP Configuration Window was particularly interesting for me because it could potentially show the registers and associated meaning through the mdf file. My project has a lot of registers. However, I have not been successful in getting this to read a mdf either which has set me back a little.
I do have the daemon up and running on Linux and am seeing heartbeat messages. I feel I might need to go back a few steps though and try to recreate your project here with an Arduino and radio instead of CAN and establish a base line for sanity.

**Comment by Dusty14** [comment]
Hi,
Just trying to compile the Generic Arduino example provided. I installed the library and get this error;
vscp_core.c:50:40: fatal error: ../events/vscp_information.h: No such file or directory
I found it in the main framework directory, but are we meant to include this in the arduino lib somehow?

**Comment by BlueAndi** [comment]
> I installed the library and get this error;
> vscp_core.c:50:40: fatal error: ../events/vscp_information.h: No such file or directory

I guess you are using v0.7.0 of the arduino library, please update to v0.7.1
The arduino library manager didn't recognized the v0.7.1 yet, as I see, so you have to update manually.

> Its a bit overwhelming at first and many things dont seem to function as expected.

Its not always "simple", as the 's' in VSCP stands for. :-) In the beginning I needed also some time get familiar with.

> The VSCP Works and especially the VSCP Configuration Window was particularly interesting for me because it could potentially show the registers and associated meaning through the mdf file. My project has a lot of registers. However, I have not been successful in getting this to read a mdf either which has set me back a little.

Especially for this, it makes sense to open an issue at https://github.com/grodansparadis/vscp so that Ake knows it and is able to fix it. If I find a little bit time this late evening, I will check it in vscpWorks.

Some time agao I created a sevice web interface to get all registers and abstractions shown, but I am using VSCP L1 ... didn't tried with L2. But this should work, e.g. see here:
![grafik](https://user-images.githubusercontent.com/9699465/51424367-ddcd2c00-1bcc-11e9-892f-21f690da63b5.png)
Maybe this can be a interim solution, until vscp works gets fixed.

The services you can find in /service/index.html

**Comment by BlueAndi** [comment]
Hmm ... the VSCP configuration window works for me, using a local mdf file.

**Comment by Dusty14** [comment]
Thanks BlueAndi, I will investigate the web interface for sure.
Sofar, I cant get anything to work as expected in vscp works accept for seeing packets. 
Sofar, I have the latest server running, I disabled the sim mode server so I could better see what was happening. I enabled the TCPIP interface. I compiled your pc example, ran this successfully and see interaction with the server - no problems here, but when I try to say do a node scan, it throws a heap of read_register messages onto the bus and reports no nodes found. 
Sorry, still trying to get my head around this so I must be doing something wrong. 
I'll try your web interface and report back.
(I may have misunderstood, but I thought Ake was taking leave for 5 years?)

**Comment by BlueAndi** [comment]
> I may have misunderstood, but I thought Ake was taking leave for 5 years?

I think you mean this post here: http://grodansparadis.com/wordpress/?p=2073
But this doesn't influence the VSCP project, so Ake is still online, responsive and hard on work for the next VSCP release.

Can you give me more details about your system?
You mentioned the esp's and raspberry pi's connected together via ethernet. Can you provide one of your MDF files too?
