### ISSUE TITLE
Bug in vscp_data_coding_getFormatByte()

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#19]
`
extern uint8_t vscp_data_coding_getFormatByte(VSCP_DATA_CODING_REPRESENTATION representation, uint8_t unit, uint8_t index)
`

should be changed to:

`
extern uint8_t vscp_data_coding_getFormatByte(VSCP_DATA_CODING_REPRESENTATION representation, uint8_t index, uint8_t unit)
`

to match rest of the code.

(or change rest of the code to match the original definition :) )

**Comment by BlueAndi** [comment]
Thanks, good finding!
