### ISSUE TITLE
Heartbeat synchronization

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#7]
How about implementing (as option) sending heartbeat event as response to segment controller heartbeat? 

I am not sure if I want it to be exclusive with heartbeat timer or conjunctive.

**Comment by BlueAndi** [comment]
If every node in the segment sends immediately a heartbeat after receiving the segment controller heartbeat, the bus load will go immediately up. I don't recommend to do this, as it can cause problems on the communication bus.

**Comment by troky** [comment]
That's true if you have a lot of nodes but in smaller system with <10 nodes and seg. controller heartbeat every 60sec this shouldn't be the problem.
Anyway, I will test it using that new timeEpoch callout you implemented recently.
