### ISSUE TITLE
Decision matrix questions

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#8]
I have some questions regarding how DM is stored in persistent memory because it is somewhat confusing.

As I can see from code DM is internally always read from _vscp_ps_access_read8()_ ignoring _VSCP_CONFIG_DM_PAGE_ and _VSCP_CONFIG_DM_OFFSET_.

I want to store DM as constant in flash to avoid excessive eeprom read operations.

Currently I am using it like this (simplified):

```
const uint8_t dm[] = { 0xFF, 0x80, 0xFF, 0x14, 0xFF, 0x25, 0x10, 0x00 };
extern uint8_t vscp_ps_access_read8(uint16_t addr) {
    uint8_t data = 0;
    if ((addr >= VSCP_PS_ADDR_DM) && (addr < VSCP_PS_ADDR_DM + VSCP_PS_SIZE_DM)) {
        data = dm[addr - VSCP_PS_ADDR_DM];
    } else {
        EEPROM_Read( addr, &data, 1);
    }

    return data;
}
```

[Specification ](http://www.vscp.org/docs/vscpspec/doku.php?id=register_abstraction_model)says: 
> If the node has implemented the decision matrix it is stored in application register space.

but I don't see DM is read thru _vscp_app_reg_readRegister()_ at all.

**Comment by BlueAndi** [comment]
It is not ignoring page and offset, but this is handled in higher layers. Because you need a mapping from the virtual register address space to the persistent memory address space, e.g. in an eeprom or data flash with eeprom emulation, etc. This mapping is automatically done by the vscp-framework. Note, that just changing e.g. the page, it doesn't change the address in the persistent memory, otherwise it would waste a lot of space there. It only matters for the access to the virtual register space.

vscp_ps_access_read8() is just the read access function to the persistent memory, as correctly figured out.

If you like to provide the DM as constant, you need to know the calculated address and size, which is in VSCP_PS_ADDR_DM and size in VSCP_PS_SIZE_DM. You found that too. Great! ;-)

And yes, the DM is in the device specific register space, thats true. But for more convenience it is handled by the core ... and please consider that the vscp-framework supports paged register access as well, which can be configured.

vscp_app_reg_readRegister() handles everything else of the register space, but is NOT called for DM access.

Why do you fear "excessive" eeprom read access?

The disadvantage is, that if you like to change the DM, you have to recompile everything.

**Comment by troky** [comment]
Well, I have 128byte i2c eeprom an I want to optimize storage space a bit :)
IMHO, excessive i2c eeprom read is waste of cpu cycles... especially when DM is fixed.

In particular project DM is fixed and it doesn't need to be changed. I am aware of that disadvantage, of course.

vscp_ps_access_read8() is very convenient method to read eeprom directly at provided address 1:1 but in this case when I read DM from other memory (code above) I am wasting VSCP_PS_SIZE_DM bytes in eeprom space or do some ugly remapping, right?

Same story with GUID... I read built-in GUID directly from MCU (STM32) not from eeprom. It is read-only and covered with [vscp specs](http://www.vscp.org/docs/vscpspec/doku.php?id=globally_unique_identifiers#mcu_stored_guid_s).

Please, correct me if I am using vscp_ps_access_read8() (or anything else) in wrong way :)

**Comment by BlueAndi** [comment]
Regarding the GUID, yes it is read-only, but the storage depends on how its manufactured. Using the MCU stored GUID is good, therefore in the current trunk you will find the possiblity to read it from external. Just enable VSCP_DEV_DATA_CONFIG_ENABLE_GUID_STORAGE_EXT and implement it in vscp_portable_readGUID().

Regarding the DM, please use the vscp_ps_access_read8() as you mentioned. Try to avoid the gap in the eeprom by
```
const uint8_t dm[] = { 0xFF, 0x80, 0xFF, 0x14, 0xFF, 0x25, 0x10, 0x00 };
extern uint8_t vscp_ps_access_read8(uint16_t addr) {
    uint8_t data = 0;
    if ((addr >= VSCP_PS_ADDR_DM) && (addr < (VSCP_PS_ADDR_DM + VSCP_PS_SIZE_DM))) {
        data = dm[addr - VSCP_PS_ADDR_DM];
    }
    /* Avoid gap in EEPROM for addresses after DM */
    else if ((VSCP_PS_ADDR_DM + VSCP_PS_SIZE_DM) <= addr) {
        EEPROM_Read(addr - VSCP_PS_SIZE_DM, &data, 1);
    }
    /* The address space in front of the DM address, can be regular used. */
    else {
        EEPROM_Read(addr, &data, 1);
    }

    return data;
}
```
Please consider the extern ```uint8_t vscp_ps_access_write8(uint16_t addr)``` as well, which is called in case of restoring factory default settings.

Just as a side note, but couldn't you use additional the eeprom emulation in the STM32? IMHO there are exsiting drivers in the SDK especially for it. Isn't it?

**Comment by troky** [comment]
Thanks for this GUID commit. I think you missed `#include "vscp_dev_data_config.h"` in vscp_portable.h

Already using STM32 eeprom emulation in other project. It is nice because it is "gap-resistant". Downside is that implementation uses 4x times more space, i.e. 2 uint16_t for 1 uint8_t. No problem when you have enough flash available. :)

**Comment by BlueAndi** [comment]
Ups ... I added it in the examples and the project, but missed it somehow in the templates. :-)

**Comment by troky** [comment]
Can you explain paged DM feature? I don't see any difference than normal DM access. In both ways vscp_ps_access_read8() is called with same params.
What is use of VSCP_CONFIG_DM_PAGE and VSCP_CONFIG_DM_OFFSET?


vscpWorks reads DM only if in page 0, i.e. 
```
<dmatrix>
      <level>1</level>
      <start page="0" offset="0" indexed="false"/>
</dmatrix>
```

if I put page="2" for example it won't be read.

**Comment by BlueAndi** [comment]
VSCP specifies a virtual register address map, where you have pages and one page contains a maximum of 256 registers. Page 0 always contains the standard VSCP registers, see https://grodansparadis.gitbooks.io/the-vscp-specification/vscp_register_abstraction_model.html

vscpWorks uses the MDF to see where the decision matrix is located and I tested it successful some minutes ago (vscpWorks Aluminium 13.1.0.10), having the decision matrix at page 1, offset 0.

The MDF file must represent the configuration of the node.
```
#define VSCP_CONFIG_DM_PAGE                     1
#define VSCP_CONFIG_DM_OFFSET                   0
```

The paged DM feature is described here: https://grodansparadis.gitbooks.io/the-vscp-specification/vscp_decision_matrix.html#general
Its for legacy support, but to be honest, I am thinking about to remove it in the future.
